// Render the local presentation, verify media and layout, and export its PDF.
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';

const runtime = process.env.DEMO_RUNTIME_MODULES ?? 'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const require = createRequire(path.join(runtime, 'playwright/package.json'));
const { chromium } = require('playwright');
const output = path.resolve(process.argv[2] ?? 'outputs/demo-latest-mp4-20260929');
const review = path.resolve(process.argv[3] ?? 'outputs/.demo-latest-mp4-review');
await fs.mkdir(review, { recursive: true });
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1360, height: 900 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(String(error)));
await page.goto(pathToFileURL(path.join(output, 'presentation.html')).href);
await page.evaluate(() => document.fonts.ready);
await page.waitForFunction(() => [...document.images].every(img => img.complete && img.naturalWidth > 0));
const slides = page.locator('.slide');
const count = await slides.count();
if (count !== 12) throw Error(`Unexpected slide count ${count}`);
const layout = await page.evaluate(() => [...document.querySelectorAll('.slide')].map((slide, index) => {
  const foot = slide.querySelector('footer').getBoundingClientRect();
  const content = slide.querySelector('.content');
  const elements = [...content.querySelectorAll('p,table,img,video,li,figcaption,h3')];
  const overflow = elements.filter(el => el.getBoundingClientRect().bottom > foot.top - 3).map(el => ({tag:el.tagName,text:el.textContent.slice(0,100),bottom:el.getBoundingClientRect().bottom,footer:foot.top}));
  return { slide:index+1, overflow };
}));
for (let i=0;i<count;i++) await slides.nth(i).screenshot({path:path.join(review,`slide-${String(i+1).padStart(2,'0')}.png`)});
await page.emulateMedia({media:'print'});
await page.pdf({path:path.join(output,'presentation.pdf'),printBackground:true,preferCSSPageSize:true});
await page.emulateMedia({media:'screen'});
await page.locator('#present').click();
await page.locator('#next').click();
if (await page.locator('.slide.current').getAttribute('id') !== 'slide-2') throw Error('Presentation navigation failed');
await page.keyboard.press('ArrowRight');
if (await page.locator('.slide.current').getAttribute('id') !== 'slide-3') throw Error('Keyboard navigation failed');
const video = page.locator('video');
await video.evaluate(v=>{v.load()});
await page.waitForFunction(()=>document.querySelector('video').readyState>=2);
await video.evaluate(v=>v.play());
await page.waitForFunction(()=>document.querySelector('video').currentTime>0.2);
const media = await video.evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight,error:v.error?.message??null,currentTime:v.currentTime}));
await video.evaluate(v=>v.pause());
await page.goto(pathToFileURL(path.join(output,'technical-summary.html')).href);
const links = await page.locator('a').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('href')));
for (const href of links) await fs.access(path.join(output,href));
const report = {slides:count,layout,browserErrors:errors,media,localLinksChecked:links.length};
await fs.writeFile(path.join(review,'browser-validation.json'),JSON.stringify(report,null,2));
await browser.close();
console.log(JSON.stringify(report,null,2));
if (errors.length || layout.some(s=>s.overflow.length)) process.exitCode=1;
